// subirPreguntas.js
// Ejecutar con: node subirPreguntas.js

const { initializeApp } = require("firebase/app");
const { getFirestore, collection, addDoc } = require("firebase/firestore");

const firebaseConfig = {
  apiKey: "AIzaSyDL6vSCeM0bL93QYROqbg4KNHdlxP6KyvA",
  authDomain: "icfes-app-20982.firebaseapp.com",
  projectId: "icfes-app-20982",
  storageBucket: "icfes-app-20982.firebasestorage.app",
  messagingSenderId: "294707517093",
  appId: "1:294707517093:web:2055240e7f65c6ffc09f4c"
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

// ── SOCIALES ────────────────────────────────────────────────────────────────
const preguntasSociales = [
  { id: 1, area: "sociales", pregunta: "Como argumento a favor del vegetarianismo, una persona afirma que consumir carne es nocivo para los humanos porque el animal sufre en el proceso, y esto produce energías negativas que perjudican al consumidor. Otra persona sostiene que el consumo de productos de origen animal es un acto amoral porque resulta del abuso del ser humano ante los demás seres vivos. ¿Cuál de las siguientes afirmaciones sobre la relación entre las opiniones presentadas NO es correcta?", opciones: ["A. Son similares, porque ambas van en contra del consumo de carne.", "B. Son complementarias, porque ambas promueven el vegetarianismo argumentando la obligación de proteger a los animales.", "C. Son diferentes, porque la primera aboga por la salud del ser humano y la segunda por el bienestar de los animales.", "D. Son disímiles, porque la primera se centra en cómo el animal afecta al ser humano y la segunda en cómo el ser humano afecta al animal."], correcta: "B", contexto: "" },
  { id: 2, area: "sociales", pregunta: "Los habitantes de un barrio de clase media se oponen a que se construyan viviendas de interés social porque afirman que las personas de escasos recursos representarían un peligro para la seguridad. ¿Cuál enunciado contiene un argumento válido en contra de esa afirmación?", opciones: ["A. Quienes ejercen la delincuencia en una zona pobre de la ciudad pueden no ser habitantes de esa zona.", "B. Entre los delincuentes nunca hay personas de escasos recursos, pues todos son adinerados gracias a sus actividades delictivas.", "C. Los delincuentes que habitan en zonas pobres dejarían de violar la ley si contaran con mejores condiciones de vida.", "D. Hay casos en que la pobreza y la falta de oportunidades llevan a una persona, en un momento de desesperación, a cometer un delito."], correcta: "A", contexto: "" },
  { id: 3, area: "sociales", pregunta: "Un rector argumenta: 'Las personas con inclinaciones homosexuales merecen ser amadas. En todos los países hay población homosexual y las preferencias sexuales son resultado de una compleja interacción de la biología con el medio ambiente. Los homosexuales pueden enseñar, siempre y cuando controlen su comportamiento y no afecten la orientación sexual de los estudiantes'. ¿Cuál enunciado del rector contiene un prejuicio cuestionable?", opciones: ["A. En todos los países hay población homosexual.", "B. Las personas con inclinaciones homosexuales, como todas las personas, merecen ser amadas.", "C. Las preferencias sexuales son el resultado de una compleja interacción de la biología con el medio ambiente.", "D. Los homosexuales pueden enseñar, siempre y cuando controlen su comportamiento y no afecten la orientación sexual de los estudiantes."], correcta: "D", contexto: "" },
  { id: 4, area: "sociales", pregunta: "¿Cuál es el orden cronológico correcto de estos magnicidios en la historia política de Colombia durante el siglo XX? 1. Asesinato de Luis Carlos Galán. 2. Asesinato de Jorge Eliécer Gaitán. 3. Asesinato de Rafael Uribe Uribe. 4. Asesinato de Álvaro Gómez Hurtado.", opciones: ["A. 2, 3, 1 y 4.", "B. 3, 2, 1 y 4.", "C. 3, 1, 2 y 4.", "D. 4, 3, 2 y 1."], correcta: "B", contexto: "" },
  { id: 5, area: "sociales", pregunta: "En Colombia se debate sobre legalizar el tráfico y consumo de drogas ilícitas. Algunos sectores proponen fortalecer la sensibilización sobre los riesgos de salud. Otros proponen endurecer las penas para productores, expendedores y consumidores. ¿Son similares las dos posiciones frente a la legalización de las drogas?", opciones: ["A. No, porque una está a favor de la legalización y la otra a favor del endurecimiento de las sanciones.", "B. Sí, porque ambas consideran que la regulación legal del consumo tiene un efecto directo sobre el narcotráfico.", "C. No, porque una plantea que la lucha debe ser por la vía de la represión y la otra por la vía de la prevención.", "D. Sí, porque ambas están en contra de la legalización y se enfocan en la protección de los consumidores."], correcta: "C", contexto: "" },
  { id: 6, area: "sociales", pregunta: "¿Cuál de los siguientes mecanismos puede ser usado para modificar la Constitución Política de Colombia?", opciones: ["A. Una consulta popular.", "B. Un plebiscito.", "C. Un referendo.", "D. Un cabildo abierto."], correcta: "C", contexto: "" },
  { id: 7, area: "sociales", pregunta: "Un presidente con alta popularidad quiere incluir la reelección presidencial indefinida en la Constitución y para tal fin quiere convocar un referendo. ¿El presidente puede hacer esto?", opciones: ["A. Sí, porque los referendos permiten reformar la Constitución.", "B. No, porque la Constitución no puede reformarla el Ejecutivo; solo a través de una Asamblea Constituyente.", "C. Sí, porque el presidente puede modificar la Constitución por su cuenta, sin acudir al poder legislativo.", "D. No, porque los referendos no permiten reformar la Constitución."], correcta: "A", contexto: "" },
  { id: 8, area: "sociales", pregunta: "Un ciudadano presentó ante el Congreso una 'iniciativa popular' para reformar varios artículos de la Ley 100 de 1993. ¿Es legalmente viable este procedimiento?", opciones: ["A. No, porque la Constitución establece que un ciudadano no tiene la facultad por sí solo para introducir propuestas de reforma a las leyes colombianas.", "B. Sí, porque la Constitución establece que se requiere un ciudadano para proponer una iniciativa popular.", "C. No, porque la Constitución establece que se requiere el 5% del censo electoral para presentar una iniciativa popular que reforme una ley.", "D. Sí, porque la Constitución establece que se requiere el 5% del apoyo de los congresistas para que la iniciativa popular se apruebe."], correcta: "C", contexto: "" },
  { id: 9, area: "sociales", pregunta: "En Colombia, las ramas del poder público pueden ejercer control político entre sí. Una rama cuenta con dos mecanismos: la citación a un debate de control político y la moción de censura. ¿Cuál es esa rama?", opciones: ["A. La Rama Electoral.", "B. La Rama Ejecutiva.", "C. La Rama Judicial.", "D. La Rama Legislativa."], correcta: "D", contexto: "" },
  { id: 10, area: "sociales", pregunta: "¿Cuál es el orden cronológico (del más antiguo al más reciente) de estas revoluciones? La Revolución mexicana, la Revolución cubana, la Revolución nicaragüense (sandinista) y la Revolución rusa.", opciones: ["A. Revolución nicaragüense, Revolución rusa, Revolución mexicana, Revolución cubana.", "B. Revolución mexicana, Revolución rusa, Revolución cubana, Revolución nicaragüense.", "C. Revolución rusa, Revolución cubana, Revolución mexicana, Revolución nicaragüense.", "D. Revolución cubana, Revolución rusa, Revolución mexicana, Revolución nicaragüense."], correcta: "B", contexto: "" },
  { id: 11, area: "sociales", pregunta: "¿Por qué las medidas del acuerdo del gobierno colombiano con el FMI en los años 1990 pueden catalogarse como 'neoliberales'?", opciones: ["A. Porque implican un manejo arbitrario de la dinámica económica del país por el gobierno nacional.", "B. Porque plantean una mayor presencia del Estado en el sector productivo como agente administrador.", "C. Porque implican la injerencia de instituciones financieras extranjeras en la política económica interna.", "D. Porque plantean reducir el tamaño del Estado y su participación en la regulación de actividades económicas."], correcta: "D", contexto: "" },
  { id: 12, area: "sociales", pregunta: "Se dice que una Constitución es la ley de leyes, la fuente de toda la jurisprudencia en un Estado de derecho. ¿Cuál es la principal utilidad de una Constitución?", opciones: ["A. Impartir justicia y orientar las acciones del Poder Ejecutivo en un Estado social de derecho.", "B. Facilitar la labor de los jueces, al asumir la tarea de impartir justicia de manera imparcial.", "C. Garantizar la paz y la prosperidad de las naciones, al expresar los acuerdos de cada ciudadano.", "D. Establecer un orden jurídico y un marco normativo que delimita el poder del Estado y establece qué es legal."], correcta: "D", contexto: "" },
  { id: 13, area: "sociales", pregunta: "La acción de tutela es un mecanismo que busca la protección inmediata de los derechos fundamentales. ¿En cuál de las siguientes situaciones se puede presentar una acción de tutela?", opciones: ["A. Cuando se vulnera el derecho a la salud, porque está en riesgo la vida de la persona.", "B. Cuando alguien es expulsado de una agremiación, a pesar de estar al día en sus pagos.", "C. Cuando se busca proteger un derecho colectivo de constituir juntas de acción comunal.", "D. Cuando se legisla sobre el derecho a la vida y el acceso a un trabajo digno para las personas."], correcta: "A", contexto: "" },
  { id: 14, area: "sociales", pregunta: "La Revolución Industrial se debió a la invención de la máquina de vapor y la concentración del capital. ¿Cuál de las siguientes afirmaciones es una consecuencia de la revolución industrial?", opciones: ["A. El traslado del campo a la ciudad y el surgimiento del proletariado urbano.", "B. El crecimiento de la población rural sobre la urbana.", "C. El nacimiento de una élite propietaria de la tierra.", "D. El desarrollo de un modelo económico para la protección del proletariado."], correcta: "A", contexto: "" },
  { id: 15, area: "sociales", pregunta: "El socialismo busca la igualdad social, política y económica. ¿Qué propone el socialismo para alcanzar este propósito?", opciones: ["A. Privatizar los medios de producción y lograr desmontar los sindicatos de las empresas transnacionales.", "B. Impulsar el consumo y la capacidad de endeudamiento de los trabajadores como factores para dinamizar la economía.", "C. Ofrecer bienes y servicios según el esquema de los tratados de libre comercio y la apertura económica.", "D. Lograr la tenencia colectiva de los medios de producción y la consolidación del poder político en las clases trabajadoras."], correcta: "D", contexto: "" },
  { id: 16, area: "sociales", pregunta: "El Consejo Académico de un colegio decidió nombrar como representantes al Consejo Estudiantil a los estudiantes con mejor desempeño, en lugar de realizar elecciones. ¿Qué situación genera esta decisión?", opciones: ["A. Que se estimule a los estudiantes a estudiar y ser mejores compañeros.", "B. Que se dificulte la disponibilidad de tiempo para el desarrollo normal de las actividades académicas.", "C. Que se vulnere el derecho de los estudiantes a tener y utilizar mecanismos de participación.", "D. Que se promueva en los estudiantes la comprensión de la importancia del Consejo Estudiantil."], correcta: "C", contexto: "" },
  { id: 17, area: "sociales", pregunta: "Un profesor universitario solo les da la palabra a los hombres para responder, porque afirma que las mujeres se extienden demasiado. ¿El profesor está vulnerando algún derecho según la Constitución?", opciones: ["A. No, pues el profesor puede hacer esto porque tiene más experiencia que sus estudiantes.", "B. Sí, ya que con su actuación el profesor está vulnerando el derecho a la igualdad.", "C. No, pues a pesar de que la actitud del profesor puede ser chocante, no es discriminatoria.", "D. Sí, porque el profesor puede justificar lo que hace si prueba que las mujeres hablan demasiado."], correcta: "B", contexto: "" },
  { id: 18, area: "sociales", pregunta: "Una compañía petrolera identificó un yacimiento en zona indígena. Fue imposible llegar a un acuerdo y el Estado le negó el permiso de explotación. ¿Cuál es la razón que mejor sustenta la decisión del Estado según la Constitución?", opciones: ["A. Garantizar el derecho a la igualdad.", "B. Garantizar el derecho a la libre asociación.", "C. Proteger la diversidad étnica y cultural.", "D. Proteger el medio ambiente."], correcta: "C", contexto: "" },
  { id: 19, area: "sociales", pregunta: "La crisis económica de 1929 en Estados Unidos también afectó a los países latinoamericanos. Para contrarrestarla, los estados adoptaron la 'sustitución de importaciones'. ¿En qué consiste esta medida?", opciones: ["A. En prohibir el ingreso de toda clase de productos extranjeros.", "B. En otorgar total libertad de producción, de cambio y de consumo.", "C. En producir internamente los bienes que tradicionalmente se traían del exterior.", "D. En dejar actuar libremente las leyes de la oferta y la demanda."], correcta: "C", contexto: "" },
  { id: 20, area: "sociales", pregunta: "El gobierno decidió construir una represa en un sitio con asentamiento indígena. Después de un largo proceso de conciliación, se acordó la construcción y que los indígenas se asentaran en otro territorio. ¿Cómo procedió el gobierno según la Constitución?", opciones: ["A. Actuó en contra de los derechos de las comunidades indígenas.", "B. Favoreció a la comunidad indígena en contra del interés general.", "C. Mostró respeto por la comunidad indígena en función del bien común.", "D. Debió hacer una consulta popular para resolver este problema."], correcta: "C", contexto: "" },
];

// ── INGLÉS ───────────────────────────────────────────────────────────────────
const preguntasIngles = [
  { id: 1, area: "ingles", contexto: "Look at the two columns. Match each description with the correct word. Available words: A. glasses, B. handbags, C. hat, D. pajamas, E. scarf, F. skirt, G. socks.", pregunta: "A person can carry things in one of these.", opciones: ["A. glasses", "B. handbags", "C. hat", "D. pajamas"], correcta: "B" },
  { id: 2, area: "ingles", contexto: "Look at the two columns. Match each description with the correct word. Available words: A. glasses, B. handbags, C. hat, D. pajamas, E. scarf, F. skirt, G. socks.", pregunta: "You wear this when you go to bed.", opciones: ["A. glasses", "B. hat", "C. scarf", "D. pajamas"], correcta: "D" },
  { id: 3, area: "ingles", contexto: "Look at the two columns. Match each description with the correct word. Available words: A. glasses, B. handbags, C. hat, D. pajamas, E. scarf, F. skirt, G. socks.", pregunta: "You cover your neck with this.", opciones: ["A. hat", "B. skirt", "C. scarf", "D. socks"], correcta: "C" },
  { id: 4, area: "ingles", contexto: "Look at the two columns. Match each description with the correct word. Available words: A. glasses, B. handbags, C. hat, D. pajamas, E. scarf, F. skirt, G. socks.", pregunta: "Some people need them to see well.", opciones: ["A. glasses", "B. handbags", "C. skirt", "D. socks"], correcta: "A" },
  { id: 5, area: "ingles", contexto: "Look at the two columns. Match each description with the correct word. Available words: A. glasses, B. handbags, C. hat, D. pajamas, E. scarf, F. skirt, G. socks.", pregunta: "These are for your feet.", opciones: ["A. hat", "B. scarf", "C. skirt", "D. socks"], correcta: "D" },
  { id: 6, area: "ingles", contexto: "Part 2: Where can you see these signs? There is a sign that reads: 'Draw a line to complete the snake and color it'.", pregunta: "Where can you see this sign?", opciones: ["A. on a rug", "B. on a test", "C. on a bookcase", "D. on a door"], correcta: "B" },
  { id: 7, area: "ingles", contexto: "Part 3: Complete the conversation. A young person speaks to an elderly woman who is carrying bags.", pregunta: "— Grandma, shall I hold those bags for you?", opciones: ["A. I'm not afraid!", "B. Where are you?", "C. That's fine.", "D. I don't know."], correcta: "C" },
  { id: 8, area: "ingles", contexto: "Part 3: Complete the conversation. A customer is asking about the price of an item in a shop.", pregunta: "— How much is that umbrella?", opciones: ["A. Anything else?", "B. 50 dollars.", "C. Cash only!", "D. It is very nice."], correcta: "B" },
  { id: 9, area: "ingles", contexto: "Part 4: Read the text about coffee. 'Coffee is popular around the world. Its blank important component is caffeine.'", pregunta: "Its ________ important component is caffeine.", opciones: ["A. much", "B. more", "C. most", "D. many"], correcta: "C" },
  { id: 10, area: "ingles", contexto: "Part 4: Coffee text. 'Coffee has been well-known blank the beginning of the 14th century.'", pregunta: "Coffee has been well-known ________ the beginning of the 14th century.", opciones: ["A. during", "B. until", "C. since", "D. for"], correcta: "C" },
  { id: 11, area: "ingles", contexto: "Part 4: Coffee text. 'Coffee has been well-known since the beginning of the 14th century, blank Sufi Yemenis started using coffee.'", pregunta: "...the beginning of the 14th century, ________ Sufi Yemenis started using coffee.", opciones: ["A. when", "B. which", "C. who", "D. where"], correcta: "A" },
  { id: 12, area: "ingles", contexto: "Part 4: Coffee text. 'It became a popular medicine blank Europeans in the 1600s.'", pregunta: "It became a popular medicine ________ Europeans in the 1600s.", opciones: ["A. among", "B. about", "C. along", "D. around"], correcta: "A" },
  { id: 13, area: "ingles", contexto: "Part 4: Coffee text. 'Caffeine was first blank in the 1800s by Ferdinand Runge.'", pregunta: "Caffeine was first ________ in the 1800s by Ferdinand Runge.", opciones: ["A. describe", "B. described", "C. describes", "D. describing"], correcta: "B" },
  { id: 14, area: "ingles", contexto: "Part 4: Coffee text. 'Some people say blank coffee isn't good.'", pregunta: "Some people say ________ coffee isn't good.", opciones: ["A. drink", "B. drinking", "C. drunk", "D. drank"], correcta: "B" },
  { id: 15, area: "ingles", contexto: "Part 4: Coffee text. 'But doctors say you blank believe this.'", pregunta: "...but doctors say you ________ believe this.", opciones: ["A. mustn't", "B. couldn't", "C. wouldn't", "D. shouldn't"], correcta: "A" },
  { id: 16, area: "ingles", contexto: "Part 4: Coffee text. 'blank many people believe coffee is bad, studies show it is good for your heart.'", pregunta: "________ many people believe coffee is bad, studies show it is good for your heart.", opciones: ["A. While", "B. Except", "C. Because", "D. So"], correcta: "A" },
  { id: 17, area: "ingles", contexto: "Part 5: James Salter article. He is best known as a novelist, but during the sixties and seventies, he worked in film making.", pregunta: "James Salter played an important part in the making of movies...", opciones: ["A. from 1960 to 1979.", "B. in 1957.", "C. after 1997.", "D. before 1957."], correcta: "A" },
  { id: 18, area: "ingles", contexto: "Part 5: James Salter article. 'Burning the Days, a short story published in The New Yorker in 1997, was adapted into a film called Passionate Falsehoods.'", pregunta: "Passionate Falsehoods is...", opciones: ["A. a newspaper.", "B. a play.", "C. a movie.", "D. a novel."], correcta: "C" },
  { id: 19, area: "ingles", contexto: "Part 5: James Salter article. 'Salter's time in the film world is both good and bad.'", pregunta: "Salter had nice and difficult times when he was...", opciones: ["A. an actor.", "B. making movies.", "C. in a different city.", "D. writing novels."], correcta: "B" },
  { id: 20, area: "ingles", contexto: "Part 5: James Salter article. 'Nick Paumgarten in The Last Book describes Salter's opinion.'", pregunta: "The Last Book was written by...", opciones: ["A. James Salter.", "B. Deborah Treisman.", "C. Nick Paumgarten.", "D. Robert Redford."], correcta: "C" },
];

// ── MATEMÁTICAS ──────────────────────────────────────────────────────────────
const preguntasMatematicas = [
  { id: 1, area: "matematicas", contexto: "", pregunta: "Si f(x) = 2x² - 3x + 1, ¿cuál es el valor de f(2)?", opciones: ["A. 3", "B. 5", "C. 7", "D. 9"], correcta: "A" },
  { id: 2, area: "matematicas", contexto: "", pregunta: "¿Cuál es el resultado de simplificar la expresión (x² - 9) / (x - 3)?", opciones: ["A. x - 3", "B. x + 3", "C. x² + 3", "D. x - 9"], correcta: "B" },
  { id: 3, area: "matematicas", contexto: "", pregunta: "En un triángulo rectángulo, los catetos miden 6 cm y 8 cm. ¿Cuánto mide la hipotenusa?", opciones: ["A. 10 cm", "B. 12 cm", "C. 14 cm", "D. 16 cm"], correcta: "A" },
  { id: 4, area: "matematicas", contexto: "", pregunta: "¿Cuál es la pendiente de la recta que pasa por los puntos (2, 3) y (4, 7)?", opciones: ["A. 1", "B. 2", "C. 3", "D. 4"], correcta: "B" },
  { id: 5, area: "matematicas", contexto: "", pregunta: "Una tienda ofrece un descuento del 20% sobre un producto que cuesta $150.000. ¿Cuánto paga el cliente?", opciones: ["A. $100.000", "B. $110.000", "C. $120.000", "D. $130.000"], correcta: "C" },
  { id: 6, area: "matematicas", contexto: "", pregunta: "¿Cuál es el conjunto solución de la ecuación 3x - 7 = 8?", opciones: ["A. x = 3", "B. x = 4", "C. x = 5", "D. x = 6"], correcta: "C" },
  { id: 7, area: "matematicas", contexto: "", pregunta: "Si el radio de un círculo es 7 cm, ¿cuál es su área? (Use π ≈ 3.14)", opciones: ["A. 143.07 cm²", "B. 153.86 cm²", "C. 163.54 cm²", "D. 173.21 cm²"], correcta: "B" },
  { id: 8, area: "matematicas", contexto: "", pregunta: "¿Cuál es el valor de log₁₀(1000)?", opciones: ["A. 2", "B. 3", "C. 4", "D. 10"], correcta: "B" },
  { id: 9, area: "matematicas", contexto: "", pregunta: "En una secuencia aritmética, el primer término es 4 y la razón común es 5. ¿Cuál es el décimo término?", opciones: ["A. 45", "B. 49", "C. 50", "D. 54"], correcta: "B" },
  { id: 10, area: "matematicas", contexto: "", pregunta: "¿Cuántas diagonales tiene un hexágono?", opciones: ["A. 6", "B. 8", "C. 9", "D. 12"], correcta: "C" },
  { id: 11, area: "matematicas", contexto: "", pregunta: "Si sen(30°) = 0.5, ¿cuánto vale cos(60°)?", opciones: ["A. 0", "B. 0.5", "C. 0.75", "D. 1"], correcta: "B" },
  { id: 12, area: "matematicas", contexto: "", pregunta: "¿Cuál es la solución del sistema de ecuaciones: x + y = 10 y x - y = 4?", opciones: ["A. x = 5, y = 5", "B. x = 6, y = 4", "C. x = 7, y = 3", "D. x = 8, y = 2"], correcta: "C" },
  { id: 13, area: "matematicas", contexto: "", pregunta: "¿Cuál es la derivada de f(x) = 3x³ - 2x + 5?", opciones: ["A. 9x² - 2", "B. 9x² + 2", "C. 3x² - 2", "D. 6x² - 2"], correcta: "A" },
  { id: 14, area: "matematicas", contexto: "", pregunta: "En una urna hay 5 bolas rojas y 3 azules. ¿Cuál es la probabilidad de sacar una bola azul?", opciones: ["A. 1/4", "B. 3/8", "C. 1/2", "D. 5/8"], correcta: "B" },
  { id: 15, area: "matematicas", contexto: "", pregunta: "¿Cuál es el volumen de un cubo con arista de 4 cm?", opciones: ["A. 16 cm³", "B. 32 cm³", "C. 48 cm³", "D. 64 cm³"], correcta: "D" },
  { id: 16, area: "matematicas", contexto: "", pregunta: "¿Cuál es el mínimo común múltiplo (MCM) de 12 y 18?", opciones: ["A. 24", "B. 36", "C. 48", "D. 72"], correcta: "B" },
  { id: 17, area: "matematicas", contexto: "", pregunta: "Si el 30% de un número es 45, ¿cuál es ese número?", opciones: ["A. 100", "B. 120", "C. 150", "D. 180"], correcta: "C" },
  { id: 18, area: "matematicas", contexto: "", pregunta: "¿Cuál es el resultado de (2³ × 2⁴)?", opciones: ["A. 2⁷", "B. 2¹²", "C. 4⁷", "D. 8⁷"], correcta: "A" },
  { id: 19, area: "matematicas", contexto: "", pregunta: "La media aritmética de los datos 4, 8, 6, 10, 12 es:", opciones: ["A. 6", "B. 7", "C. 8", "D. 9"], correcta: "C" },
  { id: 20, area: "matematicas", contexto: "", pregunta: "¿Cuál es la ecuación de la recta que tiene pendiente 3 y pasa por el punto (0, -2)?", opciones: ["A. y = 3x + 2", "B. y = 3x - 2", "C. y = -3x + 2", "D. y = -3x - 2"], correcta: "B" },
];

// ── LECTURA CRÍTICA ──────────────────────────────────────────────────────────
const preguntasLectura = [
  { id: 1, area: "lectura", contexto: "Lee el siguiente texto: 'La tecnología ha transformado profundamente la manera en que nos comunicamos. Las redes sociales permiten conectar a personas de todo el mundo en tiempo real, pero también han generado nuevos problemas como la desinformación y el aislamiento social paradójico, donde se tiene más conexiones virtuales pero menos relaciones profundas.'", pregunta: "¿Cuál es la idea principal del texto?", opciones: ["A. Las redes sociales son completamente negativas para la sociedad.", "B. La tecnología ha cambiado la comunicación generando tanto beneficios como problemas.", "C. La desinformación es el único problema de las redes sociales.", "D. Las personas prefieren las relaciones virtuales a las presenciales."], correcta: "B" },
  { id: 2, area: "lectura", contexto: "Lee el siguiente texto: 'La tecnología ha transformado profundamente la manera en que nos comunicamos. Las redes sociales permiten conectar a personas de todo el mundo en tiempo real, pero también han generado nuevos problemas como la desinformación y el aislamiento social paradójico, donde se tiene más conexiones virtuales pero menos relaciones profundas.'", pregunta: "¿Qué significa 'aislamiento social paradójico' en el contexto del texto?", opciones: ["A. Que las personas no tienen acceso a internet.", "B. Que tener más contactos virtuales no garantiza relaciones verdaderas.", "C. Que la tecnología elimina toda forma de comunicación.", "D. Que las redes sociales unen a las personas físicamente."], correcta: "B" },
  { id: 3, area: "lectura", contexto: "Lee el siguiente poema: 'Caminante, son tus huellas el camino y nada más; caminante, no hay camino, se hace camino al andar.' — Antonio Machado", pregunta: "¿Qué quiere decir el poeta con 'no hay camino, se hace camino al andar'?", opciones: ["A. Que los caminos físicos no existen.", "B. Que el futuro se construye con las decisiones y acciones propias.", "C. Que caminar es la única forma de aprender.", "D. Que mirar atrás impide avanzar."], correcta: "B" },
  { id: 4, area: "lectura", contexto: "Lee el siguiente texto argumentativo: 'Algunos defienden que el trabajo desde casa aumenta la productividad. Sin embargo, otros sostienen que genera aislamiento y dificulta la separación entre vida laboral y personal.'", pregunta: "¿Cuál es el propósito del texto?", opciones: ["A. Demostrar que el trabajo desde casa es mejor.", "B. Presentar dos posturas opuestas sobre el trabajo remoto.", "C. Convencer al lector de trabajar desde casa.", "D. Criticar a quienes trabajan desde oficinas."], correcta: "B" },
  { id: 5, area: "lectura", contexto: "Lee el siguiente texto: 'El calentamiento global es uno de los mayores desafíos de la humanidad. Las emisiones de CO₂ producidas por industrias y vehículos han elevado la temperatura del planeta, causando derretimiento de glaciares, aumento del nivel del mar y eventos climáticos extremos.'", pregunta: "Según el texto, ¿cuál es la causa principal del calentamiento global?", opciones: ["A. El derretimiento de los glaciares.", "B. Las emisiones de CO₂ de industrias y vehículos.", "C. El aumento del nivel del mar.", "D. Los eventos climáticos extremos."], correcta: "B" },
  { id: 6, area: "lectura", contexto: "Lee el siguiente texto: 'El calentamiento global es uno de los mayores desafíos de la humanidad. Las emisiones de CO₂ producidas por industrias y vehículos han elevado la temperatura del planeta, causando derretimiento de glaciares, aumento del nivel del mar y eventos climáticos extremos.'", pregunta: "¿Cuál de las siguientes es una consecuencia del calentamiento global según el texto?", opciones: ["A. El aumento de las emisiones de CO₂.", "B. El crecimiento industrial descontrolado.", "C. El derretimiento de los glaciares.", "D. La producción de vehículos contaminantes."], correcta: "C" },
  { id: 7, area: "lectura", contexto: "Lee el siguiente fragmento: 'Esa noche, mientras la lluvia golpeaba los cristales, María comprendió que algunas puertas no se vuelven a abrir. Guardó la carta sin leerla y la puso junto a las otras.'", pregunta: "¿Qué actitud muestra María en el fragmento?", opciones: ["A. Curiosidad por conocer el contenido de la carta.", "B. Resignación ante algo que ya no tiene remedio.", "C. Alegría por haber tomado la decisión correcta.", "D. Indiferencia total ante la situación."], correcta: "B" },
  { id: 8, area: "lectura", contexto: "Lee el siguiente texto: 'La lectura no solo nos informa, sino que nos transforma. A través de los libros, vivimos otras vidas, conocemos otros mundos y desarrollamos empatía hacia personas diferentes a nosotros.'", pregunta: "¿Con cuál afirmación estaría de acuerdo el autor del texto?", opciones: ["A. Leer sirve únicamente para obtener información.", "B. Solo los libros académicos tienen valor educativo.", "C. La lectura contribuye al desarrollo personal e intelectual.", "D. Leer mucho hace a las personas más solitarias."], correcta: "C" },
  { id: 9, area: "lectura", contexto: "Lee el siguiente aviso: 'NutriBien: el suplemento vitamínico que el 9 de cada 10 médicos recomiendan. ¡Mejora tu energía en solo 7 días o te devolvemos tu dinero!'", pregunta: "¿Qué estrategia persuasiva usa principalmente este aviso?", opciones: ["A. Apelación al miedo.", "B. Apelación a la autoridad médica y garantía de resultado.", "C. Apelación a la tradición.", "D. Apelación a la escasez del producto."], correcta: "B" },
  { id: 10, area: "lectura", contexto: "Lee el siguiente texto: 'Los videojuegos han sido señalados como causantes de violencia en los jóvenes. Sin embargo, múltiples estudios científicos no han encontrado una relación directa entre jugar videojuegos y comportamientos violentos.'", pregunta: "¿Cuál es la postura del autor frente a los videojuegos?", opciones: ["A. Los videojuegos definitivamente causan violencia.", "B. Los videojuegos no tienen ningún efecto en los jóvenes.", "C. La relación entre videojuegos y violencia no está científicamente probada.", "D. Solo los videojuegos cooperativos son aceptables."], correcta: "C" },
  { id: 11, area: "lectura", contexto: "Lee el siguiente refrán: 'No dejes para mañana lo que puedas hacer hoy.'", pregunta: "¿Cuál es el mensaje principal de este refrán?", opciones: ["A. Que el mañana no existe.", "B. Que es importante ser organizado con el tiempo.", "C. Que la procrastinación debe evitarse actuando con responsabilidad.", "D. Que trabajar hoy garantiza el descanso mañana."], correcta: "C" },
  { id: 12, area: "lectura", contexto: "Lee el siguiente texto: 'García Márquez nació en Aracataca, Colombia, en 1927. Su obra más conocida, Cien años de soledad, fue publicada en 1967.'", pregunta: "¿Cuántos años tenía García Márquez cuando publicó Cien años de soledad?", opciones: ["A. 35 años", "B. 40 años", "C. 45 años", "D. 55 años"], correcta: "B" },
  { id: 13, area: "lectura", contexto: "Lee el siguiente texto: 'El agua es un recurso vital. Solo el 3% del agua en la Tierra es dulce, y de ese porcentaje, la mayor parte está congelada en glaciares.'", pregunta: "¿Qué conclusión se puede extraer del texto?", opciones: ["A. El agua dulce es abundante en el planeta.", "B. Los glaciares son la mejor fuente de agua para consumo.", "C. El agua disponible para los seres humanos es un recurso escaso.", "D. El 97% del agua en la Tierra es apta para beber."], correcta: "C" },
  { id: 14, area: "lectura", contexto: "Lee el siguiente titular: 'Gobierno anuncia reducción de impuestos para pequeñas empresas.'", pregunta: "¿Qué tipo de texto es este y cuál es su función principal?", opciones: ["A. Texto literario; entretener al lector.", "B. Texto informativo; comunicar un hecho de actualidad.", "C. Texto argumentativo; convencer al lector de una idea.", "D. Texto científico; explicar un fenómeno."], correcta: "B" },
  { id: 15, area: "lectura", contexto: "Lee el siguiente fragmento: 'El maestro escribió en el tablero: 9 x 1 = 7. Los estudiantes rieron. Luego escribió correctamente el resto de la tabla. Al final preguntó: ¿Por qué solo recuerdan el error y olvidan los aciertos?'", pregunta: "¿Cuál es la enseñanza principal de este relato?", opciones: ["A. Los maestros no deben cometer errores.", "B. Las matemáticas son difíciles de aprender.", "C. Las personas tienden a recordar los errores y olvidar los logros.", "D. Los estudiantes deben corregir a sus profesores."], correcta: "C" },
  { id: 16, area: "lectura", contexto: "Lee el siguiente texto: 'La inteligencia artificial está cambiando el mercado laboral. Algunos trabajos repetitivos están siendo automatizados. Sin embargo, también se crean nuevos empleos relacionados con el desarrollo de estas tecnologías.'", pregunta: "¿Cuál es la estructura argumentativa del texto?", opciones: ["A. Presenta solo los aspectos negativos de la IA.", "B. Presenta solo los aspectos positivos de la IA.", "C. Presenta un problema y lo analiza desde dos perspectivas.", "D. Concluye que la IA no afecta el empleo."], correcta: "C" },
  { id: 17, area: "lectura", contexto: "Lee el siguiente fragmento: 'Todos los seres humanos nacen libres e iguales en dignidad y derechos y, dotados como están de razón y conciencia, deben comportarse fraternalmente los unos con los otros.' — Declaración Universal de los Derechos Humanos, Artículo 1.", pregunta: "¿Qué condición establece este artículo para el comportamiento entre personas?", opciones: ["A. Que deben obedecer al Estado.", "B. Que deben actuar con fraternidad entre sí.", "C. Que deben ser iguales en riqueza.", "D. Que deben tener las mismas creencias."], correcta: "B" },
  { id: 18, area: "lectura", contexto: "Lee el siguiente texto de opinión: 'La pena de muerte no soluciona el problema de la delincuencia. Los países que la aplican no muestran menores tasas de criminalidad. Además, existe el riesgo de ejecutar a personas inocentes.'", pregunta: "¿Cuál de los siguientes argumentos NO aparece en el texto?", opciones: ["A. La pena de muerte no reduce la criminalidad.", "B. Se pueden ejecutar personas inocentes.", "C. La pena de muerte es costosa para el Estado.", "D. Es una violación de los derechos humanos."], correcta: "C" },
  { id: 19, area: "lectura", contexto: "Lee el siguiente texto: 'Había una vez un rey que tenía tres hijos. Al morir, les dejó un cofre con una nota: el verdadero tesoro está en el trabajo y la unión. Los hijos cultivaron la tierra juntos y se hicieron prósperos.'", pregunta: "¿Cuál es la moraleja de este relato?", opciones: ["A. Los reyes siempre mienten a sus hijos.", "B. El oro es el bien más preciado.", "C. El esfuerzo conjunto y el trabajo son la verdadera riqueza.", "D. Los hijos no deben obedecer a sus padres."], correcta: "C" },
  { id: 20, area: "lectura", contexto: "Lee el siguiente texto: 'Una investigación reciente demostró que los estudiantes que duermen menos de 6 horas rinden peor en pruebas académicas. El sueño permite que el cerebro consolide la información aprendida durante el día.'", pregunta: "¿Qué relación establece el texto entre el sueño y el aprendizaje?", opciones: ["A. Dormir más de 8 horas perjudica el rendimiento académico.", "B. El sueño no tiene relación con el aprendizaje.", "C. Dormir adecuadamente favorece la consolidación del aprendizaje.", "D. Estudiar de noche es más efectivo que dormir."], correcta: "C" },
];

// ── SUBIR A FIRESTORE ────────────────────────────────────────────────────────
async function subirPreguntas() {
  const todas = [
    ...preguntasSociales,
    ...preguntasIngles,
    ...preguntasMatematicas,
    ...preguntasLectura
  ];

  console.log(`Subiendo ${todas.length} preguntas a Firestore...`);

  for (const pregunta of todas) {
    await addDoc(collection(db, "preguntas"), pregunta);
    console.log(`✅ Subida: [${pregunta.area}] ${pregunta.pregunta.substring(0, 50)}...`);
  }

  console.log("\n🎉 ¡Todas las preguntas fueron subidas exitosamente!");
  process.exit(0);
}

subirPreguntas().catch(err => {
  console.error("❌ Error:", err);
  process.exit(1);
});